

INSERT INTO BOOK(NAME, DESCRIPTION, AUTHOR, TYPE_OF_BOOK, PRICE, ISBN) VALUES
  ('BATMAN', 'THE DARK KNIGHT RETURNS', 'BOB KANE BILL FINGER', 'COMIC', '40.50', '2345234624'),
  ('SPIDER-MAN', 'WITH GREAT POWER THERE MUST ALSO COME—GREAT RESPONSIBILITY!', 'STAN LEE STEVE DITKO', 'COMIC', '42.80', '2345234638'),
  ('THE SECRET WITNESS', 'FROM THE BESTSELLING AUTHOR OF A KILLER’S WIFE COMES THE THRILLING FIRST INSTALLMENT IN THE SHEPARD & GRAY SERIES, FEATURING A YOUNG SHERIFF WHO TEAMS UP WITH A FORMER PROSECUTOR TO STOP A COPYCAT KILLER.', 'VICTOR METHOS', 'MYSTERY', '60', '2345234645'),
  ('THE SUMMER PLACE', 'WHEN HER TWENTY-TWO-YEAR-OLD STEPDAUGHTER ANNOUNCES HER ENGAGEMENT TO HER PANDEMIC BOYFRIEND, SARAH DANHAUSER IS SHOCKED. BUT THE WHEELS ARE IN MOTION.', 'JENNIFER WEINER', 'ROMANCE', '45.25', '2345234632'),
  ('THE ATTIC CHILD', 'ITS 1907, AND TWELVE-YEAR-OLD CELESTINE IS LOCKED IN THE ATTIC OF A HOUSE BY THE SEA. HE HAS BEEN FORCIBLY REMOVED FROM HIS HOME IN AFRICA AND IS TREATED AS A SERVANT.', 'LOLA JAYE', 'FICTION', '60.66', '2345234666');